export default {
    "zh": "发生了一些问题！",
    "es": "¡Algo salió mal!",
    "en": "Something went wrong!",
    "bn": "কিছু ভুল হয়েছে!",
    "hi": "कुछ गड़बड़ हो गई है!",
    "pt": "Algo deu errado!",
    "ru": "Что-то пошло не так!",
    "ja": "何かがうまくいかなかった！",
    "de": "Etwas ist schiefgelaufen!",
    "wuu": "出了些问题！",
    "jv": "Eling mlebu dhasar!",
    "ko": "뭔가 잘못되었습니다!",
    "fr": "Quelque chose s'est mal passé!",
    "vi": "Đã xảy ra lỗi gì đó!",
    "te": "ఏమి సరిగా లేదు!",
    "yue": "啲嘢唔岩啦!",
    "mr": "काहीतरी चुकलं आहे!",
    "ta": "தவறு ஏதுமில்லை!",
    "tr": "Bir şeyler yanlış gitti!",
    "ur": "کچھ غلط ہوگیا!",
    "min": "差错咯！",
    "gan": "有啲問題！",
    "gu": "કંપ્યુટરમાં કોઈ ભૂલ થઈ ગઈ છે!",
    "pl": "Coś poszło nie tak!",
    "arz": "حصل خطأ ما!",
    "uk": "Щось пішло не так!",
    "it": "Qualcosa è andato storto!",
    "hsn": "有个问题！",
    "ml": "എന്തോ തെറ്റ് ആയിതു!",
    "hak": "有嘢唔岩啦!",
    "kn": "ಏನಾದ್ರು ತಪ್ಪಾಯಿತು!",
    "or": "କିଛି ଭୁଲ ହୋଇଛି!",
    "pnb": "کجھ غلط ہوگیا!",
    "su": "Aya nuju nyesolkeun!",
    "pnj": "ਕੁਝ ਗਲਤ ਹੋ ਗਿਆ!",
    "ro": "Ceva nu a mers bine!",
    "bhj": "कुछ गड़बड़ हो गई है!",
    "azb": "چیزی اشتباه رفت!",
    "pes": "چیزی اشتباه رفت!",
    "mai": "कुछ गलत हो गया है!",
    "ha": "Wani sabon za a yi daidai!",
    "arq": "وقع خطأ ما!",
    "my": "မည္သည္ မွာ မွတ္သည့္အတိုင္း လုံးဝေလား!",
    "hr": "Nešto nije u redu!",
    "awd": "कुछ ग़लत बात हो गयी!",
    "th": "มีบางอย่างผิดพลาด!",
    "nl": "Er is iets fout gegaan!",
    "yo": "Ẹniti kò dára!",
    "sd": "ڪجهو غلط ٿو!",
    "ary": "حاجه غلط طرحت!",
    "acm": "فشخ غلط هنت!",
    "bur": "တစ္ခါတနာ မှာ မွားေနသလား!",
    "hbs": "Nesto nije u redu!",
    "nan": "有啥問題！",
    "bcl": "Mangyari, mayong tamang aramid!",
    "plw": "Talò ay ma'y problema!",
    "bxm": "Yat 'ag to lalakwe'!",
    "tet": "Aihan! Ida mak erradu.",
    "gay": "Ada hatara sana!",
    "lav": "Kludien prasi!",
    "nij": "Wa rabi kelainan!",
    "bis": "Wanem i liklik rang?",
    "bug": "Adu masalah watu!",
    "btd": "Iya semu be lahi!",
    "rom": "Ceaz'o o dhiatla dzango nushto!",
    "lin": "Kuma kuna yango!",
    "kqn": "Xae ywa nsam jwa!",
    "rmn": "Ia haves semnenqe!",
    "arg": "Mee at aar oos gange!",
    "fao": "Eitt eydnislega!",
} as {[k: string]: string}