export enum generalActionTypes {
  SET_TOKEN = 'SET_TOKEN',
  SET_IS_TABBAR_VISIBLE = 'SET_IS_TABBAR_VISIBLE',
  SET_THEME = 'SET_THEME',
  SET_CURRENT_SCREEN = 'SET_CURRENT_SCREEN',
  SET_PROFILE_HELP_SCREEN_DISPLAYED = 'SET_PROFILE_HELP_SCREEN_DISPLAYED',
  SET_IS_MAIN_MENU_FLAT_LIST = 'SET_IS_MAIN_MENU_FLAT_LIST',
  SET_APP_LOADING = 'SET_APP_LOADING',
  SET_SWIPEABLE_PANEL_PROPS = 'SET_SWIPEABLE_PANEL_PROPS',
  SET_APP_DATA = 'SET_APP_DATA',
  LOG_OUT = 'LOG_OUT',
  SET_JOB_INDUSTRIES = 'SET_JOB_INDUSTRIES',
  SET_USER_DATA = 'SET_USER_DATA',
  SET_USER_ADVERTS = 'SET_USER_ADVERTS',
  SET_USER_COMPANY = 'SET_USER_COMPANY',
  SET_USER_EVENTS = 'SET_USER_EVENTS',
  SET_CANDIDATE_MARKS = 'SET_CANDIDATE_MARKS',
  SET_CANDIDATE_NOTES = 'SET_CANDIDATE_NOTES',
  SET_USER_INVOICES = 'SET_USER_INVOICES',
}

export enum bookmarkActionTypes {
  SET_SUPER = 'SET_SUPER',
  SET_CONSIDER = 'SET_CONSIDER',
  SET_FUTURE = 'SET_FUTURE',
  SET_HISTORY = 'SET_HISTORY',
  SET_BLANK = 'SET_BLANK',
  SET_COLOR = "SET_COLOR"
}

export enum calendarActionTypes {
  ADD_EVENT = 'ADD_EVENT',
  REMOVE_EVENT = 'REMOVE_EVENT',
  EDIT_EVENT = "EDIT_EVENT",
  SAVE_QUESTIONS = "SAVE_QUESTIONS",
}


export enum advertActionTypes {
  ADD_ADVERT = 'ADD_ADVERT',
  REMOVE_ADVERT = 'REMOVE_ADVERT',
  EDIT_ADVERT = "EDIT_ADVERT"
}

export enum companyActionTypes {
  ADD_COMPANY = 'ADD_COMPANY',
  REMOVE_COMPANY = "REMOVE_COMPANY",
  EDIT_COMPANY = "EDIT_COMPANY"
}